import type { RawExamQuestionDetailResult } from "@/types/exam";

/** 파트1~4는 문항당 0~3점, 파트5는 문항당 0~5점 (TOEIC Speaking 공식 배점 기준) */
export const MOCK_EXAM_QUESTION_FEEDBACK_RAW: Record<number, RawExamQuestionDetailResult> = {
  1: {
    examId: "mock_exam_001",
    question: {
      partNumber: 1,
      questionNumber: 1,
      audioUrl: "",
      score: 2,
      maxScore: 3,
      transcript:
        "The Kingswood Community Center is recruiting volunteers. If you are looking for a way to get more involved in the community, now is your chance.",
      feedback: {
        summary: "핵심 내용은 잘 전달했지만 일부 단어의 발음과 끊어 읽기가 불안정했어요.",
        level: "양호",
        strengths: ["문장 구조를 원문 그대로 정확히 읽음", "전체적인 속도는 안정적임"],
        weaknesses: ["'community', 'volunteers' 발음의 강세가 흔들림", "구두점 기준 끊어 읽기가 다소 부자연스러움"],
        pronunciation: "대부분의 단어는 정확했지만 community, involved처럼 음절이 많은 단어에서 강세 위치가 흔들렸어요.",
        fluency: "문장 중간에 불필요한 pause가 있어 의미 단위가 아니라 단어 단위로 끊겨 들렸어요.",
        content: "원문의 내용을 빠짐없이 정확하게 읽었어요.",
        pronunciation_fluency_score: 0.62,
        content_relevance_score: 0.95,
        grammar_vocabulary: "지문을 그대로 읽는 문제라 문법적으로는 문제가 없었어요.",
        action_items: [
          "community, volunteers 등 어려운 단어의 강세를 미리 확인하고 연습하기",
          "쉼표, 마침표 단위로 의미 덩어리를 묶어 읽는 연습하기",
        ],
      },
    },
  },
  2: {
    examId: "mock_exam_001",
    question: {
      partNumber: 1,
      questionNumber: 2,
      audioUrl: "",
      score: 2,
      maxScore: 3,
      transcript:
        "Garden Gate Magazine is pleased to announce its spring landscaping contest. It is open to beginner, experienced, and professional gardeners.",
      feedback: {
        summary: "안정적으로 읽었지만 일부 구간에서 pause가 많아 흐름이 끊겼어요.",
        level: "양호",
        strengths: ["문장 전체를 누락 없이 읽음", "발음 정확도는 준수함"],
        weaknesses: ["문장 중간 pause가 잦음", "일부 자음 발음이 약함"],
        pronunciation: "전반적으로 무난했지만 landscaping, experienced에서 발음이 다소 뭉개졌어요.",
        fluency: "문장 사이 pause는 적절했지만 문장 내부에서 불필요하게 끊는 구간이 있었어요.",
        content: "지문 내용을 정확히 전달했어요.",
        pronunciation_fluency_score: 0.6,
        content_relevance_score: 0.95,
        grammar_vocabulary: "지문을 그대로 읽는 문제라 문법적으로는 문제가 없었어요.",
        action_items: ["긴 단어는 음절 단위로 끊어 먼저 연습한 뒤 문장에 붙이기", "문장 내부에서 불필요하게 멈추지 않도록 통으로 읽는 연습하기"],
      },
    },
  },
  3: {
    examId: "mock_exam_001",
    question: {
      partNumber: 2,
      questionNumber: 3,
      audioUrl: "",
      score: 2,
      maxScore: 3,
      transcript:
        "This picture shows a person working outdoors. There is some equipment on the ground and the person seems to be focused on the task.",
      feedback: {
        summary: "사진의 주요 요소는 언급했지만 위치·동작 표현이 다소 부정확했어요.",
        level: "양호",
        strengths: ["사진의 인물과 배경을 언급함", "문장 구조가 간단하고 이해하기 쉬움"],
        weaknesses: ["구체적인 동작 표현이 부족함", "위치 표현(in front of, next to 등)이 거의 없음"],
        pronunciation: "발음은 대체로 명확했어요.",
        fluency: "문장 사이 pause가 다소 길었지만 전체적인 흐름은 유지됐어요.",
        content: "사람과 사물은 언급했지만 정확한 위치나 동작까지는 설명하지 못했어요.",
        pronunciation_fluency_score: 0.68,
        content_relevance_score: 0.55,
        grammar_vocabulary: "현재진행형 사용이 다소 어색한 부분이 있었어요.",
        action_items: ["왼쪽-가운데-오른쪽 순서로 3문장 말하는 틀 연습하기", "위치 전치사(behind, next to, in front of)를 활용해 표현 다양화하기"],
      },
    },
  },
  4: {
    examId: "mock_exam_001",
    question: {
      partNumber: 2,
      questionNumber: 4,
      audioUrl: "",
      score: 2,
      maxScore: 3,
      transcript:
        "In this picture, there are several people in a room. Some of them are sitting and some are standing near the table.",
      feedback: {
        summary: "전체적인 상황은 설명했지만 세부 동작 묘사가 부족했어요.",
        level: "양호",
        strengths: ["인물 수와 배치를 언급함", "문장이 문법적으로 크게 어긋나지 않음"],
        weaknesses: ["구체적인 행동 묘사(예: 이야기하는 중, 문서를 보는 중)가 부족함", "수 일치 오류가 한 번 있었음"],
        pronunciation: "발음은 무난한 편이었어요.",
        fluency: "속도는 적절했지만 문장이 짧게 끊기는 경향이 있었어요.",
        content: "사진의 핵심 요소를 절반 정도만 설명했어요.",
        pronunciation_fluency_score: 0.65,
        content_relevance_score: 0.5,
        grammar_vocabulary: "일부 문장에서 단수/복수 일치 오류가 있었어요.",
        action_items: ["동작을 나타내는 동사(talking, holding, pointing 등) 어휘 확장하기", "주어와 동사의 수 일치를 확인하며 말하는 연습하기"],
      },
    },
  },
  5: {
    examId: "mock_exam_001",
    question: {
      partNumber: 3,
      questionNumber: 5,
      audioUrl: "",
      score: 3,
      maxScore: 3,
      transcript:
        "I cooked dinner last weekend. I made a simple pasta dish with tomatoes and garlic because it's quick and easy to prepare.",
      feedback: {
        summary: "질문에 직접적으로 답하고 구체적인 예시까지 제시한 매우 좋은 답변이었어요.",
        level: "우수",
        strengths: ["질문의 두 부분(when, what) 모두 답변함", "구체적인 예시로 신뢰도를 높임"],
        weaknesses: ["특별히 지적할 약점이 없음"],
        pronunciation: "발음이 명확하고 강세도 자연스러웠어요.",
        fluency: "pause 없이 매끄럽게 이어 말했어요.",
        content: "질문에서 요구한 정보를 모두 포함했어요.",
        pronunciation_fluency_score: 0.9,
        content_relevance_score: 0.95,
        grammar_vocabulary: "문법 오류 없이 자연스러운 문장을 구사했어요.",
        action_items: ["현재 수준을 유지하며 다양한 주제로 같은 패턴을 연습하기"],
      },
    },
  },
  6: {
    examId: "mock_exam_001",
    question: {
      partNumber: 3,
      questionNumber: 6,
      audioUrl: "",
      score: 2,
      maxScore: 3,
      transcript:
        "Yes, I plan to buy a new frying pan soon because my old one doesn't work well anymore.",
      feedback: {
        summary: "명확하게 답하고 이유도 제시했지만 설명이 다소 짧았어요.",
        level: "양호",
        strengths: ["입장을 분명하게 밝힘", "이유를 간결하게 제시함"],
        weaknesses: ["이유에 대한 추가 설명이나 예시가 부족함"],
        pronunciation: "발음은 명확했어요.",
        fluency: "속도와 리듬이 자연스러웠어요.",
        content: "이유는 제시했지만 한 문장으로 끝나 다소 짧게 느껴졌어요.",
        pronunciation_fluency_score: 0.85,
        content_relevance_score: 0.7,
        grammar_vocabulary: "문법적으로 큰 문제는 없었어요.",
        action_items: ["이유를 말한 뒤 구체적인 상황이나 경험을 한 문장 더 추가하기"],
      },
    },
  },
  7: {
    examId: "mock_exam_001",
    question: {
      partNumber: 3,
      questionNumber: 7,
      audioUrl: "",
      score: 1,
      maxScore: 3,
      transcript:
        "I think cookbook is good way for learn cooking because you can see the picture and follow the step.",
      feedback: {
        summary: "입장과 이유, 예시를 모두 제시했지만 문법 오류로 전달력이 떨어졌어요.",
        level: "보통",
        strengths: ["입장-이유-예시 구조를 시도함", "질문에 벗어나지 않는 답변을 함"],
        weaknesses: ["관사, 단수/복수 등 문법 오류가 반복됨", "일부 표현이 다소 일반적임"],
        pronunciation: "발음 자체는 이해 가능한 수준이었어요.",
        fluency: "문법을 신경 쓰느라 중간중간 머뭇거림이 있었어요.",
        content: "이유는 있었지만 다소 일반적인 수준에 머물렀어요.",
        pronunciation_fluency_score: 0.55,
        content_relevance_score: 0.6,
        grammar_vocabulary: "'a good way to learn cooking', 'follow the steps'처럼 관사와 복수형 오류가 있었어요.",
        action_items: ["관사(a/the)와 명사의 단수/복수를 의식하며 말하는 연습하기", "이유를 한 문장 더 구체화해서 설득력 높이기"],
      },
    },
  },
  8: {
    examId: "mock_exam_001",
    question: {
      partNumber: 4,
      questionNumber: 8,
      audioUrl: "",
      score: 3,
      maxScore: 3,
      transcript:
        "The conference will be held at the Hilltop Convention Center, and the participation fee is 50 dollars.",
      feedback: {
        summary: "표에서 필요한 정보를 정확하게 찾아 간결하게 전달한 매우 좋은 답변이었어요.",
        level: "우수",
        strengths: ["장소와 비용 정보를 모두 정확히 전달함", "불필요한 내용 없이 간결함"],
        weaknesses: ["특별히 지적할 약점이 없음"],
        pronunciation: "고유명사와 숫자 발음이 정확했어요.",
        fluency: "막힘 없이 자연스럽게 말했어요.",
        content: "질문에서 요구한 두 가지 정보를 정확히 전달했어요.",
        pronunciation_fluency_score: 0.92,
        content_relevance_score: 0.98,
        grammar_vocabulary: "문법 오류가 없었어요.",
        action_items: ["현재 수준을 유지하며 다른 표 형식의 문제에도 같은 방식으로 연습하기"],
      },
    },
  },
  9: {
    examId: "mock_exam_001",
    question: {
      partNumber: 4,
      questionNumber: 9,
      audioUrl: "",
      score: 3,
      maxScore: 3,
      transcript:
        "Lunch is provided by Green Trail Café from noon to 1 P.M., so you don't need to prepare your own meal.",
      feedback: {
        summary: "표의 정보를 정확히 확인하고 질문 의도에 맞게 잘 답했어요.",
        level: "우수",
        strengths: ["표에서 정확한 정보를 찾아 전달함", "질문의 두 부분에 모두 답함"],
        weaknesses: ["특별히 지적할 약점이 없음"],
        pronunciation: "발음이 명확했어요.",
        fluency: "속도와 억양이 자연스러웠어요.",
        content: "질문에서 요구한 정보를 정확하고 완결성 있게 전달했어요.",
        pronunciation_fluency_score: 0.9,
        content_relevance_score: 0.95,
        grammar_vocabulary: "문법 오류가 없었어요.",
        action_items: ["현재 수준을 유지하며 다양한 시간·장소 표현에 익숙해지기"],
      },
    },
  },
  10: {
    examId: "mock_exam_001",
    question: {
      partNumber: 4,
      questionNumber: 10,
      audioUrl: "",
      score: 1,
      maxScore: 3,
      transcript:
        "The equipment session is about choosing hiking gear, and I think Sophia Lee will talk at that time, maybe around one o'clock.",
      feedback: {
        summary: "관련 세션은 잘 찾았지만 발표자 이름과 시간이 정확하지 않았어요.",
        level: "보통",
        strengths: ["질문과 관련된 세션을 정확히 선택함", "답변 구조 자체는 안정적임"],
        weaknesses: ["발표자 이름이 실제와 다름", "시간 표현이 부정확함"],
        pronunciation: "발음은 무난했어요.",
        fluency: "'maybe' 같은 불확실한 표현이 잦아 자신감이 부족해 보였어요.",
        content: "핵심 세션은 맞췄지만 세부 정보(이름, 시간)가 표와 일치하지 않았어요.",
        pronunciation_fluency_score: 0.7,
        content_relevance_score: 0.45,
        grammar_vocabulary: "문법적으로는 큰 문제가 없었어요.",
        action_items: ["표의 이름, 시간, 숫자를 답변 전에 손으로 짚어가며 확인하기", "확신 없는 표현('maybe') 대신 표에 적힌 그대로 말하는 연습하기"],
      },
    },
  },
  11: {
    examId: "mock_exam_001",
    question: {
      partNumber: 5,
      questionNumber: 11,
      audioUrl: "",
      score: 3,
      maxScore: 5,
      transcript:
        "I think it's okay to give the gift to someone else. For example, last year I received a scarf I never wear, so I gave it to my sister who loves it. It doesn't waste the gift and makes another person happy.",
      feedback: {
        summary: "입장과 개인 경험을 잘 연결했지만 문법 오류와 반복된 연결어가 설득력을 다소 낮췄어요.",
        level: "양호",
        strengths: ["명확한 입장을 제시함", "개인 경험을 예시로 활용함"],
        weaknesses: ["문법 오류가 반복됨", "연결어 사용이 단조로움"],
        pronunciation: "발음은 이해하기 편한 수준이었어요.",
        fluency: "전체적으로 매끄러웠지만 문장이 길어지며 속도가 다소 불안정해졌어요.",
        content: "입장, 이유, 예시를 모두 포함했지만 예시 이후 결론이 다소 급하게 마무리됐어요.",
        pronunciation_fluency_score: 0.72,
        content_relevance_score: 0.8,
        grammar_vocabulary: "시제 불일치와 어색한 비교 표현이 있었어요.",
        action_items: [
          "'Opinion → Reason → Example → Result' 4단계 구조로 마무리 문장까지 준비하기",
          "같은 연결어를 반복하지 않도록 다양한 표현(In addition, On the other hand 등) 익히기",
        ],
      },
    },
  },
};
